name: Release Automation

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create mobile tags for (e.g., v1.0.3)'
        required: true
        type: string

jobs:
  move-mobile-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Move Mobile Tags
        run: |
          # Get the tag (from push or manual input)
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG="${{ github.event.inputs.version }}"
          fi
          
          echo "Processing tag: $TAG"
          
          # Validate tag format
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format: $TAG"
            exit 1
          fi
          
          # Extract version parts
          MAJOR=$(echo $TAG | cut -d. -f1)              # v1
          MINOR=$(echo $TAG | cut -d. -f1-2)            # v1.0
          
          echo "Moving mobile tags:"
          echo "  $MAJOR -> $TAG"
          echo "  $MINOR -> $TAG"
          
          # Force update mobile tags
          git tag -f $MAJOR $TAG
          git tag -f $MINOR $TAG
          
          # Push mobile tags
          git push origin $MAJOR $MINOR --force
          
          echo "✅ Mobile tags updated successfully!"

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed
            
            Automatic release for ${{ github.ref_name }}
            
            ### Mobile Tags Updated
            - `${{ github.ref_name }}` ➜ Latest patch
            - Mobile tags automatically moved for dependabot compatibility
            
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v1.0.2...${{ github.ref_name }}